sudo: false
dist: trusty
language: python
python:
- '3.5'
env:
- TONG_AN=tsingli/leku-0612-hanlo.txt
- TONG_AN=tsingli/leku-0705-hanlo.txt
install:
- pip install -r requirements.txt 
script:
- python 檢查對齊.py $TONG_AN
